### ISSUE TITLE
[MEGA ISSUE] Inconsistancy Issue while running the program

### ISSUE THREAD

**Issue by georgettica** [tegal1337/mapsdumper#2]
Hello!

I got here from hacktoberfest and started to use it.

I will create a PR to make the errors I get more visible, but will also add the errors I found so we can track progress for them

**Comment by georgettica** [comment]
@tegal1337

Please let me know if you want to solve any or all of these, I would be glad if you don't hand these issues to someone else / do them yourself as I did this to support the community AND to get some credits to hacktoberfest

let me know your thoughts when you have time

**Comment by fdciabdul** [comment]
Thanks @georgettica ,i will take a look deeply

**Comment by georgettica** [comment]
same here, dropping assignage for this (I hope what I did is helpful though)
